### ISSUE TITLE
could not load config config/prod.secret.exs

### ISSUE THREAD

**Issue by vasu-dasari** [boingram/aristochat#1]
Hi,

I have been following along your blog [Elixir and Kubernetes: Deploying Aristochat](http://www.boingram.com/2017/08/01/elixir-and-kubernetes-3.html). 

I am getting following error during `edib` phase.
```
| make[2]: Entering directory '/build'
| ** (Mix.Config.LoadError) could not load config config/prod.secret.exs
|     ** (File.Error) could not read file "/source/config/prod.secret.exs": no such file or directory
```

Can you please help me?

These are the commands I used.
```
git clone https://github.com/boingram/aristochat
cd aristochat
mix deps.get
mix release.init
mix edib --name bo.ingram/aristochat --tag initial
```

The errors I see are:
```
$ mix edib --name bo.ingram/aristochat --tag initial
==> Will use EDIB tool edib/edib-tool:1.6.0
==> Packaging your app release into a docker image. Stay tuned!
| $> docker run --rm  -v "/Users/vdasari/Developer/aristochat:/source:ro" -v "/Users/vdasari/Developer/aristochat/tarballs:/stage/tarballs:rw" -e "RELEASE_TAG=initial" -e "RELEASE_NAME=bo.ingram/aristochat" -e MIX_ENV=prod edib/edib-tool:1.6.0
==> Creating artifact (might take a while) ...
| make -f edib/prerequisites.mk
| make[1]: Entering directory '/build'
| mix hex.info
| Hex:    0.16.0
| Elixir: 1.4.5
| OTP:    19.3
| Built with: Elixir 1.4.2 and OTP 18.3.4.4
| A new Hex version is available (0.16.0 < 0.17.7), please update with `mix local.hex`
| ** (Mix.Config.LoadError) could not load config config/prod.secret.exs
|     ** (File.Error) could not read file "/source/config/prod.secret.exs": no such file or directory
|     (elixir) lib/file.ex:244: File.read!/1
|     (mix) lib/mix/config.ex:180: Mix.Config.read!/2
|     (mix) lib/mix/config.ex:217: anonymous fn/3 in Mix.Config.read_wildcard!/2
|     (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
|     (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
|     (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
|     (stdlib) erl_eval.erl:404: :erl_eval.expr/5
.
.
.
```

**Comment by boingram** [comment]
Hey, thanks for reaching out! I just updated the config file to remove the reference to the missing file, and things seem to work out alright after I did that. Thanks for letting me know!

**Comment by vasu-dasari** [comment]
Thanks for quick response. By the way, awesome tutorial.
